module darkcommand.completion.bash;

import darkcommand.command;
import darkcommand.entry;
import std.stdio : File;
import std.array : appender, Appender, join;

// Writes a bash completion script for `prog` to `output`.
// Source the script; it registers completion for the program name.
void generateBashCompletion(Program prog, File output) {
    auto buf = appender!string;
    immutable fn = "__" ~ _safe(prog.name);

    buf ~= "# Generated by darkcommand — do not edit.\n";
    _writeEntryFn(buf, fn);
    _writeDispatchFn(buf, cast(Command) prog, fn);
    _writeCompletionFns(buf, cast(Command) prog, fn, "");
    buf ~= "complete -F " ~ fn ~ " " ~ prog.name ~ "\n";

    output.write(buf[]);
}

// ── Private ───────────────────────────────────────────────────────────────────

private string _safe(string s) {
    import std.ascii : isAlphaNum;
    char[] r = s.dup;
    foreach (ref c; r) if (!isAlphaNum(c)) c = '_';
    return r.idup;
}

// Main entry point: collects the subcommand path from COMP_WORDS, then calls
// the dispatch function with the path as positional arguments.
private void _writeEntryFn(ref Appender!string buf, string fn) {
    buf ~= fn ~ "() {\n";
    buf ~= "    local -a _p=()\n";
    buf ~= "    local _i\n";
    buf ~= "    for ((_i=1; _i<COMP_CWORD; _i++)); do\n";
    buf ~= "        [[ \"${COMP_WORDS[$_i]}\" == -* ]] && continue\n";
    buf ~= "        _p+=(\"${COMP_WORDS[$_i]}\")\n";
    buf ~= "    done\n";
    buf ~= "    " ~ fn ~ "_dispatch \"${_p[@]+${_p[@]}}\"\n";
    buf ~= "}\n\n";
}

// Dispatch function: receives the subcommand path as positional args ($1, $2 …).
// Navigates the tree by shifting and recursing via nested case statements.
private void _writeDispatchFn(ref Appender!string buf, Command cmd, string fn) {
    buf ~= fn ~ "_dispatch() {\n";
    _writeCases(buf, cmd, fn, "", "    ");
    buf ~= "}\n\n";
}

// Recursive case-statement writer.  `curPath` is the bash-safe suffix for the
// completion function at the current level (empty = root).
private void _writeCases(ref Appender!string buf, Command cmd,
                          string fn, string curPath, string indent)
{
    buf ~= indent ~ "case \"${1:-}\" in\n";
    foreach (sub; cmd._subcommands) {
        immutable subPath = (curPath.length ? curPath ~ "_" : "") ~ _safe(sub.name);
        buf ~= indent ~ "    " ~ sub.name ~ ")\n";
        if (sub._subcommands.length > 0) {
            buf ~= indent ~ "        shift\n";
            _writeCases(buf, sub, fn, subPath, indent ~ "        ");
        } else {
            buf ~= indent ~ "        " ~ fn ~ "_" ~ subPath ~ "\n";
        }
        buf ~= indent ~ "        ;;\n";
    }
    // Fallback: complete at the current command level.
    immutable curFn = fn ~ (curPath.length ? "_" ~ curPath : "_root");
    buf ~= indent ~ "    *) " ~ curFn ~ " ;;\n";
    buf ~= indent ~ "esac\n";
}

// Recursively write one completion function per command node.
private void _writeCompletionFns(ref Appender!string buf, Command cmd,
                                  string fn, string curPath)
{
    _writeOneFn(buf, cmd, fn, curPath);
    foreach (sub; cmd._subcommands) {
        immutable subPath = (curPath.length ? curPath ~ "_" : "") ~ _safe(sub.name);
        _writeCompletionFns(buf, sub, fn, subPath);
    }
}

private void _writeOneFn(ref Appender!string buf, Command cmd,
                          string fn, string curPath)
{
    immutable name = fn ~ (curPath.length ? "_" ~ curPath : "_root");
    buf ~= name ~ "() {\n";
    buf ~= "    local cur=\"${COMP_WORDS[$COMP_CWORD]}\" prev=\"${COMP_WORDS[$((COMP_CWORD-1))]}\"\n";

    // Emit a `case "$prev"` block for options that have special value completion.
    bool hasPrevCases = false;
    foreach (e; cmd._entries) {
        if (e.kind == EntrySpec.Kind.flag) continue;
        if (e.completionValues.length ||
            e.completionHint != EntrySpec.CompletionHint.none) {
            hasPrevCases = true; break;
        }
    }

    if (hasPrevCases) {
        buf ~= "    case \"$prev\" in\n";
        foreach (e; cmd._entries) {
            if (e.kind == EntrySpec.Kind.flag) continue;

            string rhs;
            if (e.completionValues.length)
                rhs = "COMPREPLY=($(compgen -W \"" ~ e.completionValues.join(" ") ~
                      "\" -- \"$cur\")); return";
            else if (e.completionHint == EntrySpec.CompletionHint.file)
                rhs = "COMPREPLY=($(compgen -f -- \"$cur\")); return";
            else if (e.completionHint == EntrySpec.CompletionHint.directory)
                rhs = "COMPREPLY=($(compgen -d -- \"$cur\")); return";
            else
                continue;

            string pat;
            if (e.shortName.length && e.longName.length)
                pat = "-" ~ e.shortName ~ "|--" ~ e.longName;
            else if (e.shortName.length)
                pat = "-" ~ e.shortName;
            else
                pat = "--" ~ e.longName;

            buf ~= "        " ~ pat ~ ") " ~ rhs ~ " ;;\n";
        }
        buf ~= "    esac\n";
    }

    // Static word list: subcommands + all flag/option names.
    string[] words;
    foreach (sub; cmd._subcommands) words ~= sub.name;
    foreach (e; cmd._entries) {
        if (e.shortName.length) words ~= "-"  ~ e.shortName;
        if (e.longName.length)  words ~= "--" ~ e.longName;
        if (e.negatable)        words ~= "--no-" ~ e.longName;
    }
    words ~= "--help";

    buf ~= "    COMPREPLY=($(compgen -W \"" ~ words.join(" ") ~ "\" -- \"$cur\"))\n";
    buf ~= "}\n\n";
}
